FVI/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings
from index import views
import django.views.defaults


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^statistics/', include("statistics.urls")),
    url(r'^index/', include("index.urls")),
    url(r'^static/(?P<path>.*)$', serve, {
        'document_root': settings.STATIC_ROOT } ),
    url(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
        }),
]

handler403 = views.handler403
handler404 = views.handler404
handler500 = views.handler500

statistics/urls.py
from django.conf.urls import url
from statistics import views

app_name = "statistics"
urlpatterns = [
	#dashboard
	url(r'^statistics/$', views.statistics, name='statistics'),
	url(r'^statistics/load_cards/$', views.load_cards, name='load_cards'),
	url(r'^statistics/load_chart_hours_blocks/$', views.load_chart_hours_blocks, name='load_chart_hours_blocks'),
	url(r'^statistics/load_chart_doors/$', views.load_chart_doors, name='load_chart_doors'),
	url(r'^statistics/load_detail_table/$', views.load_detail_table, name='load_detail_table'),
	url(r'^statistics/filter_mall_detail_table/$', views.filter_mall_detail_table, name='filter_mall_detail_table'),
	url(r'^statistics/filter_door_detail_table/$', views.filter_door_detail_table, name='filter_door_detail_table'),
	#user
	url(r'^statistics/user/$', views.user, name='user'),
	url(r'^statistics/user/form_user/$', views.form_user, name='form_user'),
	url(r'^statistics/user/filter_user/$', views.filter_user, name='filter_user'),
	url(r'^statistics/user_update/([0-9]+)/$', views.user_update, name='user_update'),
	url(r'^statistics/user_status/([0-9]+)/([0-9]+)/$', views.user_status, name='user_status'),
	#networking
	url(r'^statistics/networking/$', views.networking, name='networking'),
	url(r'^statistics/grafic/$', views.grafic, name='grafic'),
	url(r'^statistics/report_networking/$', views.report_networking, name='report_networking'),
	#Camera
	url(r'^statistics/cameras/$', views.cameras, name='cameras'),
	url(r'^statistics/modal/$', views.modal, name='modal'),
	#Mapas
	url(r'^statistics/maps/$', views.maps, name='maps'),
	#Crontab
	url(r'^statistics/cron/$', views.cron, name='cron'),
	url(r'^statistics/cron/filter_cron/$', views.filter_cron, name='filter_cron'),
	url(r'^statistics/new_cron/$', views.new_cron, name='new_cron'),
	url(r'^statistics/cron_update/([0-9]+)/$', views.cron_update, name='cron_update'),
	url(r'^statistics/cron_delete/([0-9]+)/$', views.cron_delete, name='cron_delete'),
	#Funciones para apagar y encender camaras
	url(r'^statistics/protocolo/$', views.protocolo, name='protocolo'),
	url(r'^statistics/protocolo_lote/$', views.protocolo_lote, name='protocolo_lote'),
	url(r'^statistics/activate/$', views.activate, name='activate'),
	url(r'^statistics/activate_lote/$', views.activate_lote, name='activate_lote'),


]

statistics/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect
from django.db.models import Q, Max, Sum, Count, F
from django.http import HttpResponseRedirect, HttpResponse, HttpRequest, JsonResponse
from django.db import connections
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.core.exceptions import PermissionDenied
from django.template import loader
from django.core import serializers

from datetime import datetime, timedelta, date
import copy
import time
import calendar
import string, os, sys, random, smtplib, json, xlwt
from functions import  f, ip, ruta
from index.models import Role, User , UserDetail

from statistics.models import Camera, Company, Door, Dynamic, EventLog, Mall, Cron, MallMaps, Hour, ViewDetail

try:
    from hashlib import sha1 as _sha, md5 as _md5
except ImportError:
    import sha
    import md5ViewDetail
    _sha = sha.new
    _md5 = md5.new

from django.db.models import Avg
import paho.mqtt.client as mqtt
import paho.mqtt.publish as publish
from crontab import CronTab
from relay import main

def statistics(request):
	if not 'role_id' in request.session:
		return redirect('/')
	if request.session['role_id'] == 2 or request.session['role_id'] == 1:
		#Aqui defino el id del mall segun el rol del usuario que esta logueado.
		if request.session['role_id'] == 2:
			search_mall = UserDetail.objects.filter(user_id=request.session['user_id'])
			mall = search_mall[0].mall_id
			query_mall = Mall.objects.filter(active=True, id=mall).order_by('id')
			mall_id = str(mall)
		else:
			query_mall = Mall.objects.filter(active=True).order_by('id')
			mall_id = ""

		list = []
		for i in query_mall:
			i = {'mall_id': i.id,
				 'mall_name': i.mall_name
				 }
			list += [i]
		return render(request, "statistics/dashboard.html", locals())
	else:
		raise PermissionDenied




def load_cards(request):
	data_before = []
	data_now = []

	#Si son mas de las 10:00am
	if datetime.now().strftime("%H:%m:%s") > "10:00:00":
		#Establecer rangos de HOY Y AYER
		date_start = datetime.now().strftime("%Y-%m-%d 10:00:00-00") 
		date_end = datetime.now().strftime("%Y-%m-%d %H:%M:%S-00")

		date_before_start = datetime.strftime(date.today() - timedelta(1),'%Y-%m-%d 10:00:00-00')
		date_before_end = datetime.strftime(date.today() - timedelta(1),'%Y-%m-%d ')+datetime.now().strftime("%H:%M:%S-00")
	else:
		#Establecer rangos de AYER Y ANTES DE AYER
		date_start = datetime.strftime(date.today() - timedelta(1),'%Y-%m-%d 10:00:00-00')
		date_end = datetime.strftime(date.today() - timedelta(1),'%Y-%m-%d 23:59:59-00')

		date_before_start = datetime.strftime(date.today() - timedelta(2),'%Y-%m-%d 10:00:00-00')
		date_before_end = datetime.strftime(date.today() - timedelta(2),'%Y-%m-%d 23:59:59-00')

	for i in Mall.objects.all():
		qs_today = Dynamic.objects.filter(time__range=(date_start, date_end),
										  camera_id__door__mall__id=i.id)\
								  .aggregate(entry=Sum('entry'),
								  			 exit=Sum('exit'))

		qs_before = Dynamic.objects.filter(time__range=(date_before_start, date_before_end),
										   camera_id__door__mall__id=i.id)\
								   .aggregate(entry_before=Sum('entry'),
								   			  exit_before=Sum('exit'))

		data_before += [
			{'entry_before':int(qs_before['entry_before']) if qs_before['entry_before'] else 0,
			'exit_before':int(qs_before['exit_before']) if qs_before['exit_before'] else 0,
			'mall_id':i.id,}
			]

		data_now += [
			{'entry':int(qs_today['entry']) if qs_today["entry"] else 0,
			'exit':int(qs_today['exit']) if qs_today["exit"] else 0,
			'mall_id':i.id,}
			]

	data = {"data_now": data_now, "data_before": data_before}

	data = json.dumps(data)
	return HttpResponse(data)



@csrf_exempt
def load_chart_hours_blocks(request):

	if not request.POST:
		dynamic = "entry"
	else:
		dynamic = request.POST["dynamic"]

	json_data = []


	if datetime.strftime(datetime.now(),'%H:%M:%S') < '10:00:00':
		now = datetime.strftime(date.today() - timedelta(1),'%Y-%m-%d')
	else:
		now = datetime.strftime(date.today(),'%Y-%m-%d')
	
	for i in range(10,24): #Rango de horas desde las 10 hasta las 23
		element = {'hour':str(i)+':00:00'} #HH:00:00
		range1 = now+" "+str(i)+':00:00-00'
		range2 = now+" "+str(i)+':59:59-00'

		qs = Dynamic.objects.filter(time__range=(str(range1),str(range2)))\
								.values('camera_id__door__mall__mall_name')\
								.annotate(entry = Sum('entry'),exit=Sum('exit'))

		if qs:
			for k in qs:
				if dynamic == 'entry':
					element[str(k['camera_id__door__mall__mall_name'])] = int(k['entry'])
				else:
					element[str(k['camera_id__door__mall__mall_name'])] = int(k['exit'])
			json_data.append(element)

	return HttpResponse(json.dumps(json_data))


@csrf_exempt
def load_chart_doors(request):
	if datetime.strftime(datetime.now(),'%H:%M:%S') < '10:00:00':
		range1 = datetime.strftime(date.today() - timedelta(1),'%Y-%m-%d 10:00:00-00')
		range2 = datetime.strftime(date.today() - timedelta(1),'%Y-%m-%d 23:59:59-00')
	else:
		range1 = datetime.now().strftime("%Y-%m-%d 10:00:00-00") 
		range2 = datetime.now().strftime("%Y-%m-%d %H:%M:%S-00")

	if not request.POST: #GET
		mall_id = 1 if request.session["role_id"] == 1 else request.session["mall_id"]
	else: #POST
		mall_id = int(request.POST['mall_id'])

	qs = Dynamic.objects.filter(time__range = (range1,range2),
							camera_id__door__mall__id=mall_id)\
					.values('camera_id__door__door_name', 'camera_id__door__mall__mall_name')\
					.annotate(entry = Sum('entry'),exit=Sum('exit'))

	if mall_id == 1:
		colors = ['#024930', '#009e60', '#1eb53a', '#007a3d', '#5bbf21']
	elif mall_id == 2:
		colors = ['#356AC8', '#132648', '#7697D1', '#293448', '#274F95']
	elif mall_id == 3:
		colors = ['#622200', '#EF990C', '#F93C0C', '#F85600', '#F9810C']


	select = copy.copy(colors)
	select_exit = copy.copy(colors)
	entry = []
	exits = []	

	if qs:
		for data in qs:
			if not select: select=copy.copy(colors)
			color = select[0]
			del select[0]
			result = {'label':str(data['camera_id__door__door_name'])+" <b>"+str(data['entry'])+"</b>",
			'data':int(data['entry']),
			'color':color,
			}
			entry += [result]

		for data in qs:
			if not select_exit: select_exit=copy.copy(colors)
			color = select_exit[0]
			del select_exit[0]
			result = {'label':str(data['camera_id__door__door_name'])+" <b>"+str(data["exit"])+"</b>",
			'data':int(data["exit"]),
			'color':color,
			}
			exits += [result]
	

	json_return = json.dumps({'data_entry': entry, 'data_exit': exits})
	return HttpResponse(json_return)


@csrf_exempt
def load_detail_table(request):

	blocks = ["10:00:00","11:00:00","12:00:00","13:00:00",
		"14:00:00","15:00:00","16:00:00","17:00:00",
		"18:00:00","19:00:00","20:00:00","21:00:00",
		"22:00:00","23:00:00"]

	if datetime.strftime(datetime.now(),'%H:%M:%S') < '10:00:00':

		now = datetime.strftime(date.today() - timedelta(1),'%Y-%m-%d')
	else:
		now = datetime.strftime(date.today(),'%Y-%m-%d')
		
	json_table = []
	json_mall = []
	json_door = []

	for i in blocks:
		hour = i[:-3]
		time_block = str(now+" "+i+"-00")
		if request.session["role_id"] == 1:
			query_view = ViewDetail.objects.filter(time=time_block).values('time').aggregate(sum_entry=Sum('sum_entry'), sum_exit = Sum('sum_exit'))
		else:
			query_view = ViewDetail.objects.filter(time=time_block, mall_id=request.session['mall_id']).values('time').aggregate(sum_entry=Sum('sum_entry'), sum_exit = Sum('sum_exit'))
		if query_view['sum_entry'] != None and query_view['sum_exit'] != None:
			result = {'date': now,
			'time': hour,
			'sum_entry': str(query_view['sum_entry']),
			'sum_exit': str(query_view['sum_exit']),
			}
			json_table += [result]

	if request.session["role_id"] == 1:
		query_mall = Mall.objects.filter(active=True).values_list("id","mall_name")
		for data in query_mall:
			result_mall = {
			'mall_id': data[0],
			'mall_name': data[1]
			}
			json_mall += [result_mall]
		return HttpResponse(json.dumps({'table': json_table, 'mall': json_mall}))
	else:
		query_mall = Mall.objects.filter(active=True, id=request.session['mall_id']).values_list("id","mall_name")
		for data in query_mall:
			result_mall = {
			'mall_id': data[0],
			'mall_name': data[1]
			}
			json_mall += [result_mall]

		query_door = Door.objects.filter(mall_id=request.session["mall_id"]).values_list("id","door_name")
		for data in query_door:
		 	result_door = {
			'door_id': data[0],
		 	'door_name': data[1]
		 	}
	 		json_door += [result_door]

		return HttpResponse(json.dumps({'table': json_table, 'mall': json_mall, 'door': json_door}))


@csrf_exempt
def filter_mall_detail_table(request):

	blocks = ["10:00:00","11:00:00","12:00:00","13:00:00",
		"14:00:00","15:00:00","16:00:00","17:00:00",
		"18:00:00","19:00:00","20:00:00","21:00:00",
		"22:00:00","23:00:00"]

	if datetime.strftime(datetime.now(),'%H:%M:%S') < '10:00:00':

		now = datetime.strftime(date.today() - timedelta(1),'%Y-%m-%d')
	else:
		now = datetime.strftime(date.today(),'%Y-%m-%d')

	json_table = []
	json_door = []

	for i in blocks:
		hour = i[:-3]
		time_block = str(now+" "+i+"-00")

		if request.POST['mall'] == "0":
			query_view = ViewDetail.objects.filter(time=time_block).values('time').aggregate(sum_entry=Sum('sum_entry'), sum_exit = Sum('sum_exit'), sum_inside= Sum('inside'))
		else:
			query_view = ViewDetail.objects.filter(time=time_block, mall_id=request.POST['mall']).values('time', 'inside').aggregate(sum_entry=Sum('sum_entry'), sum_exit = Sum('sum_exit'), sum_inside= Sum('inside'))

		if query_view['sum_entry'] != None and query_view['sum_exit'] != None:
			result = {'date': now,
			'time': hour,
			'sum_entry': str(query_view['sum_entry']),
			'sum_exit': str(query_view['sum_exit']),
			'sum_inside': str(query_view['sum_inside']),
			}
			json_table += [result]

	query_door = Door.objects.filter(mall_id=request.POST["mall"]).values_list("id","door_name")

statistics/templates/statistics/cron.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

<div class="wrapper-content">
  <div class="container">
    <div class="row  align-items-center justify-content-between">
      <div class="col-11 col-sm-12 page-title">
        <h3 style="font-family: 'Palatino', sans-serif;">Tarea Programada</h3>

      </div>
      
    </div>
    <div class="card-header align-items-start justify-content-between flex">
      <select id="mall">
        {% if request.session.role_id != 3 %}
        <option value="fvi" selected>FVI</option>
        {% endif %}
        {% for data in mall %}
        <option value="{{data.id}}">{{data.mall_name}}</option> 
        {% endfor %} 
      </select>
      <ul class="nav nav-pills card-header-pills pull-right">
        <li class="nav-item">
         <a href="{%url 'statistics:new_cron'%}"><button type="button" class="btn btn-primary" style="background-color: #000c18; border-color: #000c18">Crear Tarea Programada</button></a>
       </li>
     </ul>
   </div>
    
   <table class="table table-striped table-bordered table-hover" id="dataTables-example">
    <thead>
      <tr>
        <th>Tarea</th>
        <th>C.Comerciales</th>
        <th>Tipo</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody id="cron_list">
      {%for data in listx %}
      <tr class="odd">
          
        <td class="center">{{data.cron_name|title}}</td>
        <td class="center">{{data.mall|title}}</td>
        {%if data.type_cron == 1 %}
        <td class="centrado"> Encender Camaras</td> 
        {%elif data.type_cron == 0 %}
        <td class="centrado"> Apagar Camaras</td> 
        {%endif%}
        
        <td><a href="{%url 'statistics:cron_update' data.id %}"><button title="Editar Tarea" class="btn btn-success btn-round mr-2"><i class="fa fa-edit"></i></button></a>
          <a href="{%url 'statistics:cron_delete' data.id %}"><button title="Eliminar Tarea" class="btn btn-danger btn-round mr-2" onclick="return confirm('¿Esta seguro que desea Eliminar la tarea del {{data.mall|title}}?')"><i class="fa fa-remove"></i></button></a>
        </td>

      </tr>


      {% endfor %}

    </tbody>
  </table>



</div>

</div>




<script type="text/javascript">

  $(document).ready(function(){
// Funcion multiselect
$('#mall').multiselect({
  buttonWidth: '20%',
  onChange: function(option, checked, select) {
    var parametros = {
      "mall_id" : $("#mall").val(),
      "csrfmiddlewaretoken": '{{ csrf_token }}'
    };
    $.ajax({
      data:  parametros,
      url:   '../../statistics/cron/filter_cron/',
      type:  'post',
      success:  function (response) {
        $("#cron_list").html(response);
      }
    });

  } 
});

});

</script>

<script>
  "use strict";
  $(document).on('ready', function() {
    $('#dataTables-example').DataTable({
      responsive: true,
      pageLength:10,
      sPaginationType: "full_numbers",
      oLanguage: {
        oPaginate: {
          sFirst: "<<",
          sPrevious: "<",
          sNext: ">", 
          sLast: ">>" 
        }
      }
    });
  });
</script>


{% endblock %}

statistics/templates/statistics/cron_list.html
{%for data in listx %}
<tr class="odd">
	<td class="center">{{data.mall|title}}</td>
	<td class="center">{{data.cron_name|title}}</td>

	
	<td><a href="{%url 'statistics:cron_update' data.mall_id %}"><button title="Editar Tarea" class="btn btn-success btn-round mr-2"><i class="fa fa-edit"></i></button></a>
          </td>
		
	</tr>
	

	{% endfor %}

statistics/templates/statistics/cron_update.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="wrapper-content">
  <div class="container">
    <div class="row  align-items-center justify-content-between">
      <div class="col-11 col-sm-12 page-title">
        <h3 style="font-family: 'Palatino', sans-serif;">Crear Tarea Programada</h3>

      </div>

    </div>
    <form role="form" id='register-form' action="" method="post" class="form-horizontal form-label-left input_mask" autocomplete="off">
      {% csrf_token %}
      <div class="row">
        <div class="col-sm-16">
          <div class="card">
            <div class="card-block">
              <h5 class="m-0">Información</h5>
              <hr> 
              <div class="row justify-content-center">
                <div class="col-md-10 ">
                  <div class="form-group">
                   <div class="input-group">
                     <div class="input-group-addon"><span class="fa fa-camera"></span></div>
                     <select class="form-control" data-live-search="true" tabindex="-1" aria-hidden="true" name="type_cron" id="type_cron" disabled="true" >
                      <option value="">Seleccione</option>
                      <option value="1"
                      {%if i.type_cron == 1%}
                      selected="selected"
                      {% endif %}>Encendido de Camaras</option>
                      <option value="0"
                      {%if i.type_cron == 0%}
                      selected="selected"
                      {% endif %}>Apagado de Camaras</option>
                      
                    </select>
                  </div>
                  <span class="help-block" id="error"></span>
                </div>
                <div class="form-group">
                 <div class="input-group">
                   <div class="input-group-addon"><span class="fa fa-pencil"></span></div>
                   <select class="form-control" data-live-search="true" tabindex="-1" aria-hidden="true" name="hour_id" id="hour_id" >
                    <option value="">Seleccione</option>
                    {% for data in hour %}
                    <option value="{{data.id}}"
                    {%if i.hour == data.id%}
                    selected="selected"
                    {%endif%}>
                  {{data.current_hour}}</option> 
                  {% endfor %}
                </select>
              </div>
              <span class="help-block" id="error"></span>
            </div>
            <div class="form-group">
             <div class="input-group">
               <div class="input-group-addon"><span class="fa fa-bars"></span></div>
               <select class="form-control" data-live-search="true" tabindex="-1" aria-hidden="true" name="mall" id="mall" disabled="true">
                <option value="">Seleccione</option>
                {% for dat in mall %}
                <option value="{{dat.id}}"
                {%if i.mall_id == dat.id%}
                selected="selected"
                {%endif%}>
                {{dat.mall_name}}
              </option>
              {%endfor%}
            </select>
          </div>
          <span class="help-block" id="error"></span>
        </div>
        <input type="hidden" id="id" name="id" value="{{i.id}}">
        <input type="hidden" id="type_cron" name="type_cron" value="{{i.type_cron}}">
      </div> 
    </div>
  </div>
  <div class="card-footer">

    <button type="submit" class="btn btn-success pull-right"><span class="fa fa-paper-plane-o"></span> Editar</button>
  </div>   
</div>
</div>
</div>



</form>
</div>

</div>



<script>

  //metodo para validar
  $('document').ready(function()
  {    

   $("#register-form").validate({

    rules:
    {
      hour_id: {
       required: true
     },
     type_cron: {
       required: true
     },
     mall_id: {
       required: true
     },

   },
   messages:
   {

    hour_id:{
      required: "Por favor ingrese una hora",
    },
    type_cron:{
      required: "Por favor ingrese tipo de tarea",
    },
    mall_id: {
     required: "Por favor seleccione un Centro Comercial",
   },
 },
 errorPlacement : function(error, element) {
   $(element).closest('.form-group').find('.help-block').html(error.html());
 },
 highlight : function(element) {
   $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
 },
 unhighlight: function(element, errorClass, validClass) {
   $(element).closest('.form-group').removeClass('has-error').addClass('has-success');
   $(element).closest('.form-group').find('.help-block').html('');
 },

 submitHandler: function(form) {
  form.submit();
  //alert('ok');
}
}); 
 })
</script>

statistics/templates/statistics/user.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<style type="text/css">
.toHide
{
 display: none;
}
</style>
<div class="wrapper-content">
 <div class="container">
  <div class="row  align-items-center justify-content-between">
      <div class="col-11 col-sm-12 page-title">
        <h3>Gestión de Usuarios</h3>
        <p>Modulo para agregar/editar e inactivar usuarios</p>
      </div>
    </div>
  <div class="row">
    <div class="col-16">
      <div class="card full-screen-container">
        <div class="card-header align-items-start justify-content-between flex">
          <select id="mall">
            {% if request.session.role_id != 2 %}
            <option value="fvi" selected>FIV</option>
            {% endif %}
            {% for data in query_mall %}
            <option value="{{data.id}}">{{data.mall_name}}</option> 
            {% endfor %} 
          </select> 
          <ul class="nav nav-pills card-header-pills pull-right">
            <li class="nav-item">
             <a href="{%url 'statistics:form_user'%}"><button type="button" class="btn btn-primary" style="background-color: #000c18; border-color: #000c18">Crear Usuario</button></a>
           </li>
         </ul>
       </div>

       <table class="table" id="dataTables-example">
        <thead>
          <tr>
            <th class="toHide"></th>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Rol</th>
            <th>C.Comerciales</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody id="users_list">
          {%for data in listx %}
          <tr class="odd">
            <td class="toHide">{{data.role_id}}</td>
            <td class="center">{{data.first_name|title}}</td>
            <td class="center">{{data.last_name|title}}</td>
            <td class="center">{{data.role_name|title}}</td>
            <td class="center">{% for dat in data.mall %}{{dat|title}}{% endfor %}</td>
            
            {%if data.active == True %}
            <td><a href="{%url 'statistics:user_update' data.user_id %}"><button title="Editar usuario" class="btn btn-success btn-round mr-2"><i class="fa fa-edit"></i></button></a>
              <a href="{%url 'statistics:user_status' data.user_id 1 %}"><button title="Desactivar usuario" class="btn btn-danger mr-2 btn-round" onclick="return confirm('¿Esta seguro que desea desactivar a {{data.first_name}}  {{data.last_name}}?')"><i class="fa fa-close"></i></button></a></td>
            {% else %}
             <td><a href="{%url 'statistics:user_status' data.user_id 2 %}"><button title="Activar Usuario" class="btn btn-info mr-2 btn-round" onclick="return confirm('¿Esta seguro que desea activar a {{data.first_name}}  {{data.last_name}}?')"><i class="fa fa-check"></i></button></a></td>
          </tr>
            {%endif%}
           
          {% endfor %}

        </tbody>
      </table>



    </div>
  </div>
</div> 
</div>
</div>




<script type="text/javascript">

  $(document).ready(function(){
// Funcion multiselect
$('#mall').multiselect({
  buttonWidth: '20%',
  onChange: function(option, checked, select) {
    var parametros = {
      "mall_id" : $("#mall").val(),
      "csrfmiddlewaretoken": '{{ csrf_token }}'
    };
    $.ajax({
      data:  parametros,
      url:   '../../statistics/user/filter_user/',
      type:  'post',
      success:  function (response) {
        $("#users_list").html(response);
      }
    });

  } 
});

});

</script>

<script>
  "use strict";
  $(document).on('ready', function() {
    $('#dataTables-example').DataTable({
      responsive: true,
      pageLength:10,
      sPaginationType: "full_numbers",
      oLanguage: {
        oPaginate: {
          sFirst: "<<",
          sPrevious: "<",
          sNext: ">", 
          sLast: ">>" 
        }
      }
    });
  });
</script>

{%endblock%}

statistics/templates/statistics/user_list.html
{%for data in listx %}
<tr>
	<td class="toHide">{{data.role_id}}</td>
	<td>{{data.first_name|title}}</td>
	<td>{{data.last_name|title}}</td>
	<td>{{data.role_name|title}}</td>
	<td>{% for dat in data.mall %}{{dat|title}}{% endfor %}</td>

	{%if data.active == True %}
	<td><a href="{%url 'statistics:user_update' data.user_id %}"><button class="btn btn-success btn-round mr-2"><i class="fa fa-edit"></i></button></a>
		<a href="{%url 'statistics:user_status' data.user_id 1 %}"><button class="btn btn-danger mr-2 btn-round" onclick="return confirm('¿Esta seguro que desea desactivar a {{data.first_name}}  {{data.last_name}}?')"><i class="fa fa-close"></i></button></a></td>
		{% else %}
		<td><a href="{%url 'statistics:user_status' data.user_id 2 %}"><button class="btn btn-info mr-2 btn-round" onclick="return confirm('¿Esta seguro que desea activar a {{data.first_name}}  {{data.last_name}}?')"><i class="fa fa-check"></i></button></a></td>
	</tr>
	{%endif%}

	{% endfor %}