FVI/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings
from index import views
import django.views.defaults


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^statistics/', include("statistics.urls")),
    url(r'^index/', include("index.urls")),
    url(r'^static/(?P<path>.*)$', serve, {
        'document_root': settings.STATIC_ROOT } ),
    url(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
        }),
]

handler403 = views.handler403
handler404 = views.handler404
handler500 = views.handler500

index/urls.py
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from index import views
from django.conf import settings

app_name = "index"
urlpatterns = [
    url(r'^$', views.index),
    url(r'^destroy_session/$', views.destroy_session, name='destroy_session'),
]

statistics/urls.py
from django.conf.urls import url
from statistics import views

app_name = "statistics"
urlpatterns = [
	#dashboard
	url(r'^statistics/$', views.statistics, name='statistics'),
	url(r'^statistics/load_cards/$', views.load_cards, name='load_cards'),
	url(r'^statistics/load_chart_hours_blocks/$', views.load_chart_hours_blocks, name='load_chart_hours_blocks'),
	url(r'^statistics/load_chart_doors/$', views.load_chart_doors, name='load_chart_doors'),
	url(r'^statistics/load_detail_table/$', views.load_detail_table, name='load_detail_table'),
	url(r'^statistics/filter_mall_detail_table/$', views.filter_mall_detail_table, name='filter_mall_detail_table'),
	url(r'^statistics/filter_door_detail_table/$', views.filter_door_detail_table, name='filter_door_detail_table'),
	#user
	url(r'^statistics/user/$', views.user, name='user'),
	url(r'^statistics/user/form_user/$', views.form_user, name='form_user'),
	url(r'^statistics/user/filter_user/$', views.filter_user, name='filter_user'),
	url(r'^statistics/user_update/([0-9]+)/$', views.user_update, name='user_update'),
	url(r'^statistics/user_status/([0-9]+)/([0-9]+)/$', views.user_status, name='user_status'),
	#networking
	url(r'^statistics/networking/$', views.networking, name='networking'),
	url(r'^statistics/grafic/$', views.grafic, name='grafic'),
	url(r'^statistics/report_networking/$', views.report_networking, name='report_networking'),
	#Camera
	url(r'^statistics/cameras/$', views.cameras, name='cameras'),
	url(r'^statistics/modal/$', views.modal, name='modal'),
	#Mapas
	url(r'^statistics/maps/$', views.maps, name='maps'),
	#Crontab
	url(r'^statistics/cron/$', views.cron, name='cron'),
	url(r'^statistics/cron/filter_cron/$', views.filter_cron, name='filter_cron'),
	url(r'^statistics/new_cron/$', views.new_cron, name='new_cron'),
	url(r'^statistics/cron_update/([0-9]+)/$', views.cron_update, name='cron_update'),
	url(r'^statistics/cron_delete/([0-9]+)/$', views.cron_delete, name='cron_delete'),
	#Funciones para apagar y encender camaras
	url(r'^statistics/protocolo/$', views.protocolo, name='protocolo'),
	url(r'^statistics/protocolo_lote/$', views.protocolo_lote, name='protocolo_lote'),
	url(r'^statistics/activate/$', views.activate, name='activate'),
	url(r'^statistics/activate_lote/$', views.activate_lote, name='activate_lote'),


]

index/templates/index/footer.html
<!-- jQuery first, then Tether, then Bootstrap JS. -->
<script src="{% static 'js/jquery-2.1.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery-ui.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/bootstrap4alpha/js/tether.min.js' %}" ></script> 
<script src="{% static 'vendor/bootstrap4alpha/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery.validate.min.js' %}" ></script>
<!--Cookie js for theme chooser and applying it --> 
<script src="{% static 'vendor/cookie/jquery.cookie.js' %}"  type="text/javascript"></script>
<!-- Circular chart progress js --> 
<script src="{% static 'vendor/cicular_progress/circle-progress.min.js' %}" type="text/javascript"></script>
<!--sparklines js--> 
<script src="{% static 'vendor/sparklines/jquery.sparkline.min.js' %}" type="text/javascript' %}" ></script>
<!-- jvectormap JavaScript --> 
<script src="{% static 'vendor/jquery-jvectormap/jquery-jvectormap.js' %}" ></script> 
<script src="{% static 'vendor/jquery-jvectormap/jquery-jvectormap-world-mill-en.js' %}" ></script>   
<!-- chart js --> 
<script src="{% static 'vendor/chartjs/Chart.bundle.min.js' %}" type="text/javascript"></script> 
<script src="{% static 'vendor/chartjs/utils.js' %}" type="text/javascript"></script> 
<!-- spincremente js --> 
<script src="{% static 'vendor/spincrement/jquery.spincrement.js' %}" type="text/javascript"></script> 
<script src="{% static 'vendor/spincrement/jquery.spincrement.min.js' %}" type="text/javascript"></script> 
<!-- DataTables JavaScript --> 
<script src="{% static 'vendor/datatables/js/jquery.dataTables.min.js' %}" ></script> 
<script src="{% static 'vendor/datatables/js/dataTables.bootstrap4.js' %}" ></script> 
<script src="{% static 'vendor/datatables/js/dataTables.responsive.min.js' %}" ></script> 
<!--multiselct js--> 
<script src="{% static 'vendor/loumultiselect/js/jquery.multi-select.js" type="text/javascript" ></script> 
<!--bootstrap multiselct js--> 
<script src="{% static 'vendor/bootstrap-multiselect-master/dist/js/bootstrap-multiselect.js' %}" type="text/javascript"></script>
<!-- Morris Charts JavaScript --> 
<script src="{% static 'vendor/raphael/raphael.min.js' %}"></script> 
<!--script src="{% static 'vendor/morrisjs/morris-data.js' %}" ></script--> 
<script src="{% static 'vendor/morrisjs/morris.min.js' %}"></script> 
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
<!-- flexslider js --> 
<script src="{% static 'vendor/flexslider/jquery.flexslider-min.js' %}" type="text/javascript' %}"></script> 
<!--multiselct js--> 
<script src="{% static 'vendor/loumultiselect/js/jquery.multi-select.js' %}" type="text/javascript"></script> 
<!--bootstrap multiselct js--> 
<script src="{% static 'vendor/bootstrap-multiselect-master/dist/js/bootstrap-multiselect.js' %}" type="text/javascript"></script> 
<!-- custome template js --> 
<script src="{% static 'js/adminux.js' %}" type="text/javascript' %}" ></script> 
<script src="{% static 'js/dashboard1.js' %}" type="text/javascript' %}" ></script>
<script src="{% static 'js/dashboard2.js' %}" type="text/javascript' %}" ></script>
<script src="{% static 'js/dashboard1_light.js' %}" type="text/javascript' %}" ></script>
<!--EasyZoom Js-->
<script src="{% static 'js/easyzoom.js' %}" type="text/javascript' %}" ></script>
<!-- Date picker  js--> 
<!-- script type="text/javascript" src="{% static 'vendor/bootstrap-datepicker-1.6.4-dist/js/bootstrap-datepicker.min.js"></script --> 



<script type="text/javascript">
$(document).ready(function() {
    //Función para imponer el tiempo de estadía de los mensajes emergentes de la página.
    setTimeout(function() {
        $("#mensajes_almacenados").fadeOut(5000);
    },3500);

});
</script>
<!-- Fin del Codigo JAVASCRIPT -->

</body>
</html>

index/templates/index/header.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="/static/favicon.ico">
  <title>Fondo de Valores Inmobiliarios</title>
  <!-- Fontawesome icon CSS -->
  <link rel="stylesheet" href="/static/vendor/font-awesome-4.7.0/css/font-awesome.min.css" type="text/css">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="/static/vendor/bootstrap4alpha/css/bootstrap.css" type="text/css">
  <!-- DataTables Responsive CSS -->
  <link href="/static/vendor/datatables/css/dataTables.bootstrap4.css" rel="stylesheet">
  <link href="/static/vendor/datatables/css/responsive.dataTables.min.css" rel="stylesheet">
  <!-- jvectormap CSS -->
  <link href="/static/vendor/jquery-jvectormap/jquery-jvectormap-2.0.3.css" rel="stylesheet">
  <!-- Adminux CSS -->
  <link rel="stylesheet" href="/static/css/blue_header_sidebar_adminux.css" type="text/css">
  <!-- multiselect CSS -->
  <link rel="stylesheet" href="/static/vendor/loumultiselect/css/multi-select.css" type="text/css">
  <!-- Bootstrap multielect CSS -->
  <link rel="stylesheet" href="/static/vendor/bootstrap-multiselect-master/dist/css/bootstrap-multiselect.css" type="text/css">
  <!-- date picker CSS -->
  <link rel="stylesheet" href="/static/vendor/bootstrap-datepicker-1.6.4-dist/css/bootstrap-datepicker.css"   type="text/css">
  <link rel="stylesheet" href="/static/css/jquery-ui.css"   type="text/css">
  <!-- Morris Charts CSS -->
  <link href="/static/vendor/morrisjs/morris.css" rel="stylesheet">
  <link rel="stylesheet" href="/static/css/blue_header_sidebar_adminux.css" type="text/css">
  <!--EasyZoom CCS-->
  <link rel="stylesheet" href="/static/css/easyzoom.css" type="text/css">

  <link rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css"
  integrity="sha384-OHBBOqpYHNsIqQy8hL1U+8OXf9hH6QRxi0+EODezv82DfnZoV7qoHAZDwMwEJvSw"
  crossorigin="anonymous">
  {% block extrahead %}{% endblock %}

  <body class="menuclose menuclose-right">
    <!-- Page Loader -->
    <div class="loader_wrapper align-items-center text-center">
      <div class="load7 load-wrapper">
        <img src="/static/img/logo.png" alt="" class="loading_img">
        <div class="loader"> Cargando... </div>
        <div class="clearfix"></div>
        <br>
      </div>
    </div>
    <!-- Page Loader Ends -->
    <header class="navbar-fixed">
      <nav class="navbar navbar-toggleable-md navbar-inverse bg-faded">
        <div class="sidebar-left"> 
          {% if request.session.role_id != 3 %}
          <a class="navbar-brand imglogo" href="{% url 'statistics:statistics' %}"></a>
          <button class="btn btn-link icon-header mr-sm-2 pull-right menu-collapse" >
            <span class="fa fa-bars"></span> 
          </button>
          {% else %}
          <a class="navbar-brand imglogo"></a>
          {% endif %}
        </div>
        <div class="d-flex mr-auto"> &nbsp;</div>
        <div class="sidebar-right pull-right " >
          <ul class="navbar-nav  justify-content-end">
            <li class="nav-item">
              <label style="margin-top: 8px; color: white; font-size: 14px;"><label style="font-family: 'Palatino', sans-serif; font-size:16px">{{request.session.user_name}}</label></label>
            </li>
            <li><a href="{% url 'index:destroy_session' %}" class="btn btn-link icon-header" ><span class="fa fa-sign-out"></span></a></li>
          </ul>
        </div>
      </nav>
    </header>

    <div class="sidebar-left">
      <ul class="nav flex-column in" id="side-menu">


        <li class="title-nav"><label style="font-family: 'Palatino', sans-serif;">MENU</label></li>
        {% if request.session.role_id != 3 %}
        
        <li class="nav-item ">
          <a href="javascript:void(0)" class="menudropdown nav-link">
            <label style="font-family: 'Palatino', sans-serif; font-weight: bold;">Dashboard<i class="fa fa-angle-down "></i></label></a>
            <ul class="nav flex-column nav-second-level ">
              <li class=" nav-item">
                <a  href="{%url 'statistics:statistics'%}" class="nav-link ">
                  <i class="fa fa-globe"></i><label style="font-family: 'Palatino', sans-serif;">Dashboard General</label>
                </a>
              </li>
              <li class="nav-item"><a class="nav-link" href="{%url 'statistics:networking'%}"><i class="fa fa-dashboard"></i><label style="font-family: 'Palatino', sans-serif;">Reportes</label></a></li>

              <li class="nav-item"><a class="nav-link" href="{%url 'statistics:maps'%}"><i class="fa fa-map-marker"></i><label style="font-family: 'Palatino', sans-serif;">Ver Mapas</label></a></li>

            </ul>

          </li>

          {% endif %}
          {% if request.session.role_id != 2 %}

          <li class="nav-item "> <a href="{%url 'statistics:cameras'%}" class="menudropdown nav-link"><label style="font-family: 'Palatino', sans-serif; font-weight: bold;">Apagar/Encender camaras</label></a>

          </li>

          {% endif %}

           

          <li class="nav-item "> <a href="javascript:void(0)" class="menudropdown nav-link"><label style="font-family: 'Palatino', sans-serif; font-weight: bold;">Configuración</label><i class="fa fa-angle-down "></i></a>
            <ul class="nav flex-column nav-second-level ">
             
             {% if request.session.role_id != 3 %}
              
              <li class=" nav-item"><a  href="{%url 'statistics:user'%}" class="nav-link "><i class="fa fa-user"></i> <label style="font-family: 'Palatino', sans-serif; ">Usuarios y operadores</label></a></li>
              
              {% endif %}
              
              <!-- {% if request.session.role_id != 2 %}

              <li class="nav-item "> <a href="javascript:void(0)" class="menudropdown nav-link"><label style="font-family: 'Palatino', sans-serif; font-weight: bold;">Tareas Programadas</label><i class="fa fa-angle-down "></i></a>
                <ul class="nav flex-column nav-second-level ">

                  <li class=" nav-item"><a  href="{%url 'statistics:cron'%}" class="nav-link "><i class="fa fa-pencil"></i> <label style="font-family: 'Palatino', sans-serif; ">Encendido y Apagado</label></a></li>

                </ul>
              </li> 
              {% endif %} -->


            </ul>
          </li>




        </ul>
        <br>
        <br>
      </div>



      {% include "index/mensajes.html" %}

index/templates/index/mensajes.html
<!--Muestra los mensajes almacenados -->
<div id="mensajes_almacenados" style="position:absolute; min-width:230px; z-index: 999999; margin:0px 0 0 37%;">
{% if messages %}
    <div class="messages">
    {% for message in messages %}
        <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <!-- Sale color verde -->
           <div class="alert alert-success alert-dismissible fade in" role='alert'>
                <button class="close" type='button' data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <i class="fa fa-check-circle"></i>
                <strong> {{ message }}</strong>
            </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <!-- Sale color rojo -->
           <div class="alert alert-danger alert-dismissible fade in" role='alert'>
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <i class="fa fa-exclamation-triangle"></i>
                <strong> {{ message }}</strong>
            </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
        <!-- Sale color amarillo -->
           <div class="alert alert-warning alert-dismissible fade in" role='alert'>
                <button class="close" type='button' data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <i class="fa fa-exclamation-triangle"></i>
                <strong> {{ message }}</strong>
            </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
        <!-- Sale color azul -->
           <div class="alert alert-info alert-dismissible fade in" role='alert'>
                <button class="close" type='button' data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <i class="fa fa-info-circle"></i>
                <strong> {{ message }}</strong>
            </div>
        {% endif %}
        </div>
    {% endfor %}
    </div>
{% endif %}
</div>

index/templates/index/sign-in5.html
{%load staticfiles%}


<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="{% static 'img/Favicon Vikua/favicon.ico' %}">
<title>Fondo de Valores Inmobiliarios</title>
<!-- Fontawesome icon CSS -->
<link href="{% static 'vendor/font-awesome-4.7.0/css/font-awesome.min.css' %}" type="text/css" rel="stylesheet">
<!-- Bootstrap CSS -->
<link href="{% static 'vendor/bootstrap4alpha/css/bootstrap.css' %}" type="text/css" rel="stylesheet">
<!-- Adminux CSS -->
<link href="{% static 'css/blue_header_sidebar_adminux.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'css/personalized.css' %}" type="text/css" rel="stylesheet">
</head>

<body class="menuclose menuclose-right">
<figure class="background_small"> <img src="/static/img/login_bg.jpg" style="opacity: 0.9 !important"> </figure>
<!-- Page Loader -->
<div class="loader_wrapper align-items-center text-center">
  <div class="load7 load-wrapper">
    <img src="{% static 'img/FVI/VIKUA.png' %}" alt="" class="loading_img">
    <div class="loader"> Cargando... </div>
    <div class="clearfix"></div>
    <br>
  </div>
</div>
<!-- Page Loader Ends -->


<header class="navbar-fixed">
<nav class="navbar navbar-toggleable-md sign-in-header">
  <div class="sidebar-left">  <a class="navbar-brand imglogo"></a> </div>
  <div class="col"></div>
  <div class="sidebar-right pull-right" >

</nav>

</header>

<div class="wrapper-content-sign-in ">
{% include "index/mensajes.html" %}
  <div class="container text-center"><br><br>
    <form class="form-signin1 white" method="post">
    {% csrf_token %}
      <h2 class="tex-black mb-4">Iniciar Sesión</h2>
      <label  class="sr-only">Email</label>
      <div class="input-group"> <span class="input-group-addon"><i class="fa fa-user"></i></span>
        <input type="text" class="form-control" placeholder="Email address" id="email" name="email">
      </div>
      <br>
      <label class="sr-only">Password</label>
      <div class="input-group"> <span class="input-group-addon" ><i class="fa fa-key"></i></span>
        <input type="password" class="form-control" placeholder="Password" id="password" name="password">
      </div>
      <br>
      <!--div class="checkbox">
        <label class="form-check-label active">
          <input type="checkbox" class="form-check-input">
          <i class="fa fa-check"></i></label>
        Recordarme </div-->
      <button type="submit" class="btn btn-lg btn-primary btn-round">Iniciar sesión</button><br>
      <!--a href="" class="btn btn-link mt-2">Olvidaste la contraseña?</a-->
    </form>
   
  

  </div>
 
</div>
 

<!-- jQuery first, then Tether, then Bootstrap JS. -->

<script src="/static/js/jquery-2.1.1.min.js" type="text/javascript"></script>

<script src="/static/vendor/bootstrap4alpha/js/tether.min.js"></script> 

<script src="/static/vendor/bootstrap4alpha/js/bootstrap.min.js" type="text/javascript"></script> 

<!--Cookie js for theme chooser and applying it --> 
<script src="/static/vendor/cookie/jquery.cookie.js"  type="text/javascript"></script> 

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug --> <script src="/static/js/ie10-viewport-bug-workaround.js"></script> <script>
            "use strict";
            $('input[type="checkbox"]').on('change', function(){
                $(this).parent().toggleClass("active")
                $(this).closest(".media").toggleClass("active");
            }); 
        $(window).on("load", function(){
            /* loading screen */
            $(".loader_wrapper").fadeOut("slow");
        });
    </script>
</body>
</html>

index/templates/index/sign-in6.html
{%load staticfiles%}


<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="{% static 'img/Favicon Vikua/favicon-192x192.png' %}">
<title>Kompanio</title>
<!-- Fontawesome icon CSS -->
<link rel="stylesheet" href="{% static 'vendor/font-awesome-4.7.0/css/font-awesome.min.css' %}" type="text/css">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'vendor/bootstrap4alpha/css/bootstrap.css' %}" type="text/css">

<!-- Adminux CSS -->
<link rel="stylesheet" href="{% static 'css/blue_header_sidebar_adminux.css' %}" type="text/css">
<link href="{% static 'css/personalized.css' %}" type="text/css" rel="stylesheet">
</head>
<body class="menuclose menuclose-right">
<figure class="background"> <img src="{% static 'img/FVI/Fondo-4.png' %}" alt="Adminux- sign in "> </figure>
<!-- Page Loader -->
<div class="loader_wrapper align-items-center text-center">
  <div class="load7 load-wrapper">
    <img src="{% static 'img/FVI/VIKUA.png' %}" alt="" class="loading_img">
    <div class="loader"> Cargando... </div>
    <div class="clearfix"></div>
    <br>
  </div>
</div>
<!-- Page Loader Ends -->


<header class="navbar-fixed">
  <div class="row">

    <nav class="navbar navbar-toggleable-md sign-in-header">
      <div class="sidebar-left">  <a class="navbar-brand imglogo" href="#"></a> </div>
      <div class="col"></div>
      <!--   <div class="sidebar-right pull-right" >
      <ul class="navbar-nav  justify-content-end">
      <li><a href="#" class="btn btn-link text-white" >Need Help ?</a></li>
      <li><a href="index.html" class="btn btn-primary " >Register</a></li>
    </ul>
  </div> -->
</nav>
  </div>
  <div class="row">
    {% include "index/mensajes.html" %}
  </div>
</header>

<div class="wrapper-content-sign-in p-0">


  <div class="row">
    <div class="col-md-8 col-lg-8 text-center vertical-center" id="partII">
      <div class="row-fixed">
        <img src="{% static 'img/FVI/Logo_Kompanio.png' %}" class="fit-image pull-right sha">

      </div>
    </div>
  </div>

    <div class="col-md-8 text-left side_signing_full">

      <form class="form-signin1 full_side text-white "  method="post" style="margin-top: 35%">
        {% csrf_token %}
        <h2 class="tex-black mb-4">Iniciar Sesión</h2>
        <label  class="sr-only">Email</label>
        <input type="text" class="form-control login" placeholder="Email" id="email" name="email">
        <br>
        <label class="sr-only">Password</label>
        <input type="password" class="form-control login" placeholder="Password" id="password" name="password">
        <br>
        {% now "H:i:s" as hour %}
        {% if hour < "10:00:00" %}
        <button type="button" class="btn btn-lg btn-primary btn-round" data-toggle="modal" data-target="#modal_hora">Iniciar sesión</button>
        {% else %}
        <button type="submit" class="btn btn-lg btn-primary btn-round">Iniciar sesión</button><br>
        {% endif %}
        <br>
        <br>
        <!-- <p class="mt-3"><a href="#" class="text-white">Signup here!</a> <br>
          <a href="" class="">Forgot password?</a></p> -->
      

      <br>
    </div>
  </div>

<footer class="footer-content row  justify-content-between align-items-center">
    <div class="col-sm-8"><!-- This template is designed by <a href="http://www.maxartkiller.in" target="_blank" class="">www.maxartkiller.in</a></div>
    <div class="col-sm-8 text-right"> --><label href="#" target="_blank" class="text-white">Vikua | Todos los derechos reservados | Vikua 2018</label>
  </footer>
</div>

<!-- Modal -->

<div class="modal dark_bg fade" id="modal_hora" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel2" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Mensaje de Kompanio</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
      </div>
      <div class="modal-body"> Estimado Usuario. La información que se mostrará en el dashboard
        a continuación, son datos totalizados para el día de ayer. El conteo del día de hoy comenzará
        a ejecutarse a partir de las 10am.
       </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-lg btn-primary btn-round">Iniciar sesión</button><br>
      </div>
    </div>
  </div>
</div>

</form>

<!-- jQuery first, then Tether, then Bootstrap JS. -->

<script src="{% static 'js/jquery-2.1.1.min.js' %}" type="text/javascript"></script>

<script src="{% static 'vendor/bootstrap4alpha/js/tether.min.js' %}"></script>

<script src="{% static 'vendor/bootstrap4alpha/js/bootstrap.min.js' %}" type="text/javascript"></script>

<!--Cookie js for theme chooser and applying it -->
<script src="{% static 'vendor/cookie/jquery.cookie.js' %}"  type="text/javascript"></script>

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug --> <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
<script>
            "use strict";
            $('input[type="checkbox"]').on('change', function(){
                $(this).parent().toggleClass("active")
                $(this).closest(".media").toggleClass("active");
            });
        $(window).on("load", function(){
            /* loading screen */
            $(".loader_wrapper").fadeOut("slow");
        });

//         function randombg(){
//            var random= Math.floor(Math.random() * 6) + 0;
//            var bigSize = ["url('{% static 'img/FVI/Fondo-1.png' %}')",
//                           "url('https://sobreturismo.es/wp-content/uploads/natur-canaima.jpg')",
//                           "url('https://upload.wikimedia.org/wikipedia/commons/6/6b/Bella_Caracas.JPG')",
//                           "url('http://imagenes.superate.com/blog/salto-angel-venezuela9.jpg')",
//                           "url('https://upload.wikimedia.org/wikipedia/commons/6/6b/Bella_Caracas.JPG')",
//                           "url('http://imagenes.superate.com/blog/salto-angel-venezuela9.jpg')"];
//            document.getElementById("random").style.backgroundImage=bigSize[random];
// }
    </script>
</body>
</html>